name: ğŸŒéƒ¨ç½²ç«™ç‚¹

on:
  # æ¯å½“ push åˆ° main åˆ†æ”¯æ—¶è§¦å‘éƒ¨ç½²
  # Deployment is triggered whenever a push is made to the main branch.
  push:
    branches: [main]
  # æ‰‹åŠ¨è§¦å‘éƒ¨ç½²
  # Manually trigger deployment
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # â€œæœ€è¿‘æ›´æ–°æ—¶é—´â€ ç­‰ git æ—¥å¿—ç›¸å…³ä¿¡æ¯ï¼Œéœ€è¦æ‹‰å–å…¨éƒ¨æäº¤è®°å½•
          # "Last updated time" and other git log-related information require fetching all commit records.
          fetch-depth: 0

      - name: ğŸ”¨å®‰è£…nodejs
        uses: actions/setup-node@v4
        with:
          # é€‰æ‹©è¦ä½¿ç”¨çš„ node ç‰ˆæœ¬
          node-version: 22

      # å®‰è£…ä¾èµ–
      # Install dependencies
      - name: ğŸ“¦å®‰è£…ä¾èµ–
        run: npm i



      # è¿è¡Œæ„å»ºè„šæœ¬
      # Run the build script
      - name:  ğŸ’»æ„å»ºç«™ç‚¹
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run docs:build


      # æŸ¥çœ‹ workflow çš„æ–‡æ¡£æ¥è·å–æ›´å¤šä¿¡æ¯
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: ğŸŒéƒ¨ç½²åˆ° GitHub Pages 
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
          target_branch: gh-pages
          # éƒ¨ç½²ç›®å½•ä¸º VuePress çš„é»˜è®¤è¾“å‡ºç›®å½•
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
